import { RedditSubmission } from '@model/reddit/RedditSubmission';
import { RedditComment } from '@model/reddit/RedditComment';

export const redditSubmissions: RedditSubmission[] = [
  { 
    label: 'Reddit Submission', 
    properties: { 
      "all_awardings": [],
      "allow_live_comments": false,
      "author": "Captersian",
      "author_flair_css_class": null,
      "author_flair_richtext": [],
      "author_flair_text": null,
      "author_flair_type": "text",
      "author_fullname": "t2_6e2xf4i8",
      "author_patreon_flair": false,
      "author_premium": false,
      "awarders": [],
      "can_mod_post": false,
      "contest_mode": false,
      "created_utc": 1620816776,
      "domain": "self.energy",
      "full_link": "https://www.reddit.com/r/energy/comments/nalu34/i_burn_50_metric_tons_plantmatter_per_day_with_my/",
      "gildings": {},
      "id": "nalu34",
      "is_crosspostable": true,
      "is_meta": false,
      "is_original_content": false,
      "is_reddit_media_domain": false,
      "is_robot_indexable": true,
      "is_self": true,
      "is_video": false,
      "link_flair_background_color": "",
      "link_flair_richtext": [],
      "link_flair_text_color": "dark",
      "link_flair_type": "text",
      "locked": false,
      "media_only": false,
      "no_follow": true,
      "num_comments": 0,
      "num_crossposts": 0,
      "over_18": false,
      "parent_whitelist_status": "all_ads",
      "permalink": "/r/energy/comments/nalu34/i_burn_50_metric_tons_plantmatter_per_day_with_my/",
      "pinned": false,
      "pwls": 6,
      "retrieved_on": 1620816787,
      "score": 1,
      "selftext": "Within the last three years I drove 37265 km. My average gasoline consuption is 6.4 l/100km. So I burned 2385l gasoline in three years. \n\nMother nature needs 23 metric tons plantmatter and a lot of time and pressure for one liter gasoline. Multiplied by 2385l gasoline, I burned 54855 metric tons plantmatter within the last three years what is equal to about 50 tons per day. \n\nI would like to know how much square km forest this is but I did not found valid numbers for the weight per square km forest.",
      "send_replies": true,
      "spoiler": false,
      "stickied": false,
      "subreddit": "energy",
      "subreddit_id": "t5_2qhkd",
      "subreddit_subscribers": 111363,
      "subreddit_type": "public",
      "suggested_sort": "new",
      "thumbnail": "self",
      "title": "I burn 50 metric tons plantmatter per day with my car!",
      "total_awards_received": 0,
      "treatment_tags": [],
      "upvote_ratio": 1.0,
      "url": "https://www.reddit.com/r/energy/comments/nalu34/i_burn_50_metric_tons_plantmatter_per_day_with_my/",
      "whitelist_status": "all_ads",
      "wls": 6
    }      
  },
];

export const redditComments: RedditComment[] = [
  { 
    label: 'Reddit Comment', 
    properties: { 
      "all_awardings": [],
      "associated_award": null,
      "author": "NinjaKoala",
      "author_flair_background_color": null,
      "author_flair_css_class": null,
      "author_flair_richtext": [],
      "author_flair_template_id": null,
      "author_flair_text": null,
      "author_flair_text_color": null,
      "author_flair_type": "text",
      "author_fullname": "t2_5uy7g",
      "author_patreon_flair": false,
      "author_premium": false,
      "awarders": [],
      "body": "There's the question, though, of whether the uneconomic ones are keeping renewables off the grid, or natural gas. A carbon tax would allow nuclear to compete better with fossil fuels, and stay on if they reduce fossil fuel use overall.",
      "collapsed_because_crowd_control": null,
      "comment_type": null,
      "created_utc": 1620780178,
      "gildings": {},
      "id": "gxsr4v4",
      "is_submitter": false,
      "link_id": "t3_n9u3fy",
      "locked": false,
      "no_follow": true,
      "parent_id": "t1_gxroir1",
      "permalink": "/r/energy/comments/n9u3fy/the_controversial_future_of_nuclear_power_in_the/gxsr4v4/",
      "retrieved_on": 1620820075,
      "score": 2,
      "send_replies": true,
      "stickied": false,
      "subreddit": "energy",
      "subreddit_id": "t5_2qhkd",
      "top_awarded_type": null,
      "total_awards_received": 0,
      "treatment_tags": []
    }      
  },
];